name: CI - EmailSender

on:
  push:
    paths:
      - "Services/EmailSender/**"
  pull_request:
    paths:
      - "Services/EmailSender/**"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore solution
        run: dotnet restore LifeSync.slnx
      - name: Build solution
        run: dotnet build LifeSync.slnx --configuration Release --no-restore
      # - name: Run service tests (if any)
      #   run: |
      #     tests=$(find tests -type f \( -iname "*emailsender*.csproj" -o -iname "*email*.csproj" -o -iname "*test*.csproj" -o -iname "*tests*.csproj" \))
      #     if [ -n "$tests" ]; then
      #       for t in $tests; do
      #         dotnet test "$t" --no-build --verbosity normal || exit $?
      #       done
      #     else
      #       echo "No tests found for EmailSender"
      #     fi

  docker_build_and_publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build \
            -f Services/EmailSender/EmailSender.API/Dockerfile \
            -t ghcr.io/victormoraessantos/lifesync-emailsenderapi:latest \
            .

      - name: Push da imagem para GHCR
        run: docker push ghcr.io/victormoraessantos/lifesync-emailsenderapi:latest
