name: CI - TaskManager

on:
  push:
    paths:
      - "Services/TaskManager/**"
  pull_request:
    paths:
      - "Services/TaskManager/**"
  workflow_dispatch: {}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore solution
        run: dotnet restore LifeSync.sln
      - name: Build solution
        run: dotnet build LifeSync.sln --configuration Release --no-restore

      - name: Login no GitHub Container Registry
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build \
            -f Services/TaskManager/TaskManager.API/Dockerfile \
            -t ghcr.io/victormoraessantos/lifesync-taskmanager:latest \
            .

      - name: Push da imagem para GHCR
        run: docker push ghcr.io/victormoraessantos/lifesync-taskmanager:latest
