name: CI/CD - WebApp

on:
  push:
    paths:
      - "Services/WebApp/**"
  pull_request:
    paths:
      - "Services/WebApp/**"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - name: Restore solution
        run: dotnet restore LifeSync.slnx
      - name: Build solution
        run: dotnet build LifeSync.slnx --configuration Release --no-restore
      # - name: Run webapp tests (if any)
      #   run: |
      #     tests=$(find tests -type f \( -iname "*webapp*.csproj" -o -iname "*web*.csproj" -o -iname "*test*.csproj" -o -iname "*tests*.csproj" \))
      #     if [ -n "$tests" ]; then
      #       for t in $tests; do
      #         dotnet test "$t" --no-build --verbosity normal || exit $?
      #       done
      #     else
      #       echo "No tests found for WebApp"
      #     fi

  docker_build_and_push:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login no GitHub Container Registry
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build \
            -f Services/WebApp/LifeSync.API/Dockerfile \
            -t ghcr.io/victormoraessantos/lifesync-webappapi:latest \
            .

      - name: Push da imagem para GHCR
        run: docker push ghcr.io/victormoraessantos/lifesync-webapp:latest

  deploy_to_kubernetes:
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify namespace access
        run: kubectl get deployments -n lifesync

      - name: Update image in deployment
        run: |
          kubectl set image deployment/taskmanager-api \
            taskmanager-api=ghcr.io/victormoraessantos/lifesync-taskmanagerapi:${{ github.sha }} \
            -n lifesync

      - name: Rollout status
        run: kubectl rollout status deployment/taskmanager-api -n lifesync --timeout=5m

      - name: Get deployment info
        run: kubectl get pods -n lifesync -l app=taskmanager-api -o wide
